# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uses < Formula
  desc "use secure environment variables in dev"
  homepage "https://github.com/malikashish8/uses"
  version "0.0.23"

  on_macos do
    url "https://github.com/malikashish8/uses/releases/download/v0.0.23/uses_0.0.23_darwin_x86_64.tar.gz"
    sha256 "80e8e6727804d3e41c0b55d3dc36efb97a15d2515f0936a076ec36e96362c6c7"

    def install
      bin.install "uses"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Uses
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/malikashish8/uses/releases/download/v0.0.23/uses_0.0.23_linux_x86_64.tar.gz"
      sha256 "1e58f677a55d62d51cad9d572a3d7b1313049b302e1ec795a746a3dc3ab858b8"

      def install
        bin.install "uses"
      end
    end
  end
end
