name: "Semgrep Scan"

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3

      - run: semgrep ci
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/r
            p/security-audit
            p/golang
            p/secrets
